global:
  scrape_interval: 15s  # How frequently to scrape targets

scrape_configs:
  - job_name: 'localstack'
    static_configs:
      - targets: ['host.docker.internal:4566']  # LocalStack's default endpoint

